### ISSUE TITLE
Add quoting to scalar

### ISSUE THREAD

**Issue by juliansci** [mrzard/OpenExchangeRatesBundle#9]
Not quoting the scalars is deprecated since Symfony3.1 and will throw ParseException in 4.0.
Add quotes before and after a %.

  ```
  open_exchange_rates_service:
        class: %open_exchange_rates_service.class%
        arguments:
            app_id:            %open_exchange_rates_service.api_id%
            api_configuration: %open_exchange_rates_service.api_configuration%
            client:            "@open_exchange_rates_service.guzzle_client"
```

Thanks!

**Comment by mrzard** [comment]
Fixed via commit 70e1733, tag v2.1.2, feel free to create your own PR if you find anything else :)

Thanks!

**Comment by mrzard** [comment]
Also I just realised this was already fixed in v3 branch, which is the one geared towards Symfony3

**Comment by juliansci** [comment]
Ok, next time PR! Thanks

**Comment by mrzard** [comment]
> Ok, next time PR! Thanks

No, thank you!  :+1:
